# Generated by Django 6.0.4 on 2026-04-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='featured_image',
            new_name='profile_image',
        ),
    ]
